services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: microblog
      MYSQL_USER: microblog
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - microblog-network

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USE_TLS: ${MAIL_USE_TLS}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      ADMINS: ${ADMINS}
      DATABASE_URL: mysql+pymysql://microblog:${MYSQL_PASSWORD}@mysql/microblog
    networks:
      - microblog-network

networks:
  microblog-network:
    driver: bridge
